### ISSUE TITLE
Scroll position resets when moving across history

### ISSUE THREAD

**Issue by NoahTheDuke** [neurosnap/neovimcraft#103]
Hey there! Love the website. When i use this on my iPhone, if I click on a link and then press the Back button, my scroll position resets to the top of the page. This can be quite annoying when I’ve scrolled down quite far and have to find my spot again.

**Comment by neurosnap** [comment]
Greetings!  I agree that is quite annoying.  I'll need to look into why scroll position is not preserved.  Also happy to accept any PRs that attempt to fix it.

**Comment by neurosnap** [comment]
Fixed with https://github.com/neurosnap/neovimcraft/pull/201
