### ISSUE TITLE
Missed typo in resources.json

### ISSUE THREAD

**Issue by Theory-of-Everything** [neurosnap/neovimcraft#13]
Missed a little typo in resources.json
[This line](https://github.com/neurosnap/neovimcraft/blob/179e10b0e362375618bb824d86148eabc72c8275/src/lib/resources.json#L1831)
Should be
```
"tags": ["preconfigured-configurations"]
```
Instead of
```
"tags": ["proconfigured-configurations"]
```

**Comment by neurosnap** [comment]
fixed ty
