### ISSUE TITLE
`complementree.nvim` moved to sourcehut

### ISSUE THREAD

**Issue by vigoux** [neurosnap/neovimcraft#175]
Hi, I realized that `complementree.nvim` was listed here.

I moved the plugin to sourcehut today, and wanted to let you know.

I also realized that this is the first plugin listed here to be hosted on sourcehut.

Thanks for this !

**Comment by neurosnap** [comment]
I'm a fan of sourcehut so I'll make sure it renders properly.

**Comment by vigoux** [comment]
If possible, I'd also like to advertise [`azy.nvim`](https://sr.ht/~vigoux/azy.nvim/) in here !

Both plugins are hosted on sr.ht !

By the way, thanks for this, it really helps with the discoverability of plugins !

**Comment by neurosnap** [comment]
Np, have you ever worked with sr.ht's graphql api?

**Comment by vigoux** [comment]
Nope (neither with any GraphQL), but I might help to search for resources !

What are you searching for ?

**Comment by vigoux** [comment]
Hey, after a little search, I came accross a tool to work with sourcehut graphql APIs:
https://meta.sr.ht/graphql
https://git.sr.ht/graphql

I hope this helps !

**Comment by neurosnap** [comment]
Yes thank you.  This is the data we need from sourcehut: https://github.com/neurosnap/neovimcraft/blob/50f657023d912bcd9a062e75fde4ae64e070d5c9/scripts/process.ts#L189

**Comment by neurosnap** [comment]
Hey thanks for your help.  I'd be delighted if you took a stab at implementation and happy to step in where needed.  For stars, watchers, and forks, I would just set those to 0.

**Comment by vigoux** [comment]
Hi, I am honestly not able to help much further: I have never worked with this kind of tools...

I'll see if I have time at some point, but that make take a while, sorry !

**Comment by neurosnap** [comment]
I added both the repos mentioned here, they should show up in neovimcraft later today
