### ISSUE TITLE
README is not detected when in .github directory

### ISSUE THREAD

**Issue by JakeRoggenbuck** [neurosnap/neovimcraft#19]
Example of plugin without readme
![image](https://user-images.githubusercontent.com/35516367/145754149-73e200f5-ff7b-47eb-ae46-2fa10eed9d70.png)

I checked the plugin's github and at first I could not see the readme file, but it was displaying something so it had to be somewhere.

It looks like github allows readmes to be in the .github directory.
![image](https://user-images.githubusercontent.com/35516367/145754440-9736aa9f-bcc2-4319-8de2-97296de4a000.png)

**Comment by JakeRoggenbuck** [comment]
p.s. neovimcraft is super cool! Thank you for making it

**Comment by neurosnap** [comment]
Thanks for submitting this issue!  I have updated the fetch script to use the github api to detect the repository's readme.  Your example can be seen live here: https://neovimcraft.com/plugin/siduck76/NvChad
