### ISSUE TITLE
Add treesj (new plugin)

### ISSUE THREAD

**Issue by Wansmer** [neurosnap/neovimcraft#191]
Hello! Thanks for helping people search good plugins!
I wrote a new plugin. It will be cool if you add it to your web-site: https://github.com/Wansmer/treesj

**Comment by neurosnap** [comment]
Please feel free to submit a PR: https://github.com/neurosnap/neovimcraft#want-to-submit-a-plugin

**Comment by Wansmer** [comment]
Submit #192
