### ISSUE TITLE
Replace FZTerm.nvim with OneTerm.nvim

### ISSUE THREAD

**Issue by LoricAndre** [neurosnap/neovimcraft#2]
Hi ! I'm the author of both plugins in the title of the issue, thank you very much for including my plugin in your list !
The first is deprecated and replaced by the second. Is it possible to remove FZTerm and replace it with [OneTerm.nvim](https://github.com/LoricAndre/oneterm.nvim) ?

**Comment by neurosnap** [comment]
Done!  Thanks for the heads up!
