### ISSUE TITLE
Bug: `make resource` fails when trying to contribute

### ISSUE THREAD

**Issue by chrisgrieser** [neurosnap/neovimcraft#298]
![CleanShot 2023-04-11 at 12 34 45@2x](https://user-images.githubusercontent.com/73286100/231136380-8035e442-a2be-4c56-bc1b-7d4ef027bc32.png)

**Comment by neurosnap** [comment]
Hi!

Could you please try running: `deno run --allow-write --reload ./src/scripts/resource.ts`

**Comment by chrisgrieser** [comment]
yep, that works.
