### ISSUE TITLE
Allow filtering and sorting of plugins

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [neurosnap/neovimcraft#4]
Liking the site.

I think for people like me who are already pretty tuned-in to plugins organizing by star doesn't help much because you kinda know if you will be using coc.nvim pretty early on. 

Would love if we could sort and filter this list by things like update date so we can see the new stuff coming out.

**Comment by mcchrish** [comment]
Additionally, the default sorting should be newest added plugins first.

**Comment by neurosnap** [comment]
Thanks for the feedback!

I added sorting by stars, created at, and updated at -- data grabbed from github.

We currently do not store when a resource was added to our system so sorting by that would require recording that data.

I'll think about adding that metadata soon.

**Comment by neurosnap** [comment]
Marking as completed!  Thanks again!
