### ISSUE TITLE
Website no-longer secure?

### ISSUE THREAD

**Issue by sspencerwire** [neurosnap/neovimcraft#436]
Greetings, The website, as of today, shows insecure in the browser when attempting to load. 

Thank you for what you do!
Steve

**Comment by Froxcey** [comment]
You'll see why when you switch to http (insecure) protocol.

**Comment by neurosnap** [comment]
Looks like the domain expired, trying to get it back up

**Comment by neurosnap** [comment]
Should be resolved now please confirm.

**Comment by sspencerwire** [comment]
I can confirm this is resolved @neurosnap. Thank you!
