### ISSUE TITLE
Plugin suggestions: plantuml.nvim, id3.nvim

### ISSUE THREAD

**Issue by itaranto** [neurosnap/neovimcraft#525]
Hello, I 'd like to add this two plugins:
- https://gitlab.com/itaranto/plantuml.nvim
- https://gitlab.com/itaranto/id3.nvim

It's shameless self-promotion... I know :)

Why I didn't add them through a PR? I just don't want to install Deno.

Thanks.

**Comment by adigitoleo** [comment]
You don't really need to install it, just add the metadata for your entries into `data/manual.json`. Check some previous PRs for examples.
