### ISSUE TITLE
Add overview.nvim

### ISSUE THREAD

**Issue by adigitoleo** [neurosnap/neovimcraft#526]
I have just tagged an alpha release of [overview.nvim](https://sr.ht/~adigitoleo/overview.nvim/) [GitHub mirror](https://github.com/adigitoleo/overview.nvim) which provides a simple dynamic floating table-of-contents sidebar buffer for markup files. It can also be used to just list/navigate all the LSP symbols for a code buffer (experimental, replacement for the default qflist version of `vim.lsp.buf.document_symbol()`). Maybe some would find it useful as a minimal/floatwin alternative to some of the larger navigation/LSP plugins.

If it's a good fit I can try to work on a PR sometime. I plan to maintain it at the moment at least. It's got a vim helpfile.

**Comment by neurosnap** [comment]
Please feel free to submit a PR
